HEADERS = \
        ./editor/qscintilla/Qsci/qsciglobal.h \
        ./editor/qscintilla/Qsci/qsciscintilla.h \
        ./editor/qscintilla/Qsci/qsciscintillabase.h \
        ./editor/qscintilla/Qsci/qsciabstractapis.h \
        ./editor/qscintilla/Qsci/qsciapis.h \
        ./editor/qscintilla/Qsci/qscicommand.h \
        ./editor/qscintilla/Qsci/qscicommandset.h \
        ./editor/qscintilla/Qsci/qscidocument.h \
        ./editor/qscintilla/Qsci/qscilexer.h \
        ./editor/qscintilla/Qsci/qscilexeravs.h \
        ./editor/qscintilla/Qsci/qscilexerbash.h \
        ./editor/qscintilla/Qsci/qscilexerbatch.h \
        ./editor/qscintilla/Qsci/qscilexercmake.h \
        ./editor/qscintilla/Qsci/qscilexercoffeescript.h \
        ./editor/qscintilla/Qsci/qscilexercpp.h \
        ./editor/qscintilla/Qsci/qscilexercsharp.h \
        ./editor/qscintilla/Qsci/qscilexercss.h \
        ./editor/qscintilla/Qsci/qscilexercustom.h \
        ./editor/qscintilla/Qsci/qscilexerd.h \
        ./editor/qscintilla/Qsci/qscilexerdiff.h \
        ./editor/qscintilla/Qsci/qscilexerfortran.h \
        ./editor/qscintilla/Qsci/qscilexerfortran77.h \
        ./editor/qscintilla/Qsci/qscilexerhtml.h \
        ./editor/qscintilla/Qsci/qscilexeridl.h \
        ./editor/qscintilla/Qsci/qscilexerjava.h \
        ./editor/qscintilla/Qsci/qscilexerjavascript.h \
        ./editor/qscintilla/Qsci/qscilexerjson.h \
        ./editor/qscintilla/Qsci/qscilexerlua.h \
        ./editor/qscintilla/Qsci/qscilexermakefile.h \
        ./editor/qscintilla/Qsci/qscilexermarkdown.h \
        ./editor/qscintilla/Qsci/qscilexermatlab.h \
        ./editor/qscintilla/Qsci/qscilexeroctave.h \
        ./editor/qscintilla/Qsci/qscilexerpascal.h \
        ./editor/qscintilla/Qsci/qscilexerperl.h \
        ./editor/qscintilla/Qsci/qscilexerpostscript.h \
        ./editor/qscintilla/Qsci/qscilexerpo.h \
        ./editor/qscintilla/Qsci/qscilexerpov.h \
        ./editor/qscintilla/Qsci/qscilexerproperties.h \
        ./editor/qscintilla/Qsci/qscilexerpython.h \
        ./editor/qscintilla/Qsci/qscilexerruby.h \
        ./editor/qscintilla/Qsci/qscilexerspice.h \
        ./editor/qscintilla/Qsci/qscilexersql.h \
        ./editor/qscintilla/Qsci/qscilexertcl.h \
        ./editor/qscintilla/Qsci/qscilexertex.h \
        ./editor/qscintilla/Qsci/qscilexerverilog.h \
        ./editor/qscintilla/Qsci/qscilexervhdl.h \
        ./editor/qscintilla/Qsci/qscilexerxml.h \
        ./editor/qscintilla/Qsci/qscilexeryaml.h \
        ./editor/qscintilla/Qsci/qscimacro.h \
        ./editor/qscintilla/Qsci/qsciprinter.h \
        ./editor/qscintilla/Qsci/qscistyle.h \
        ./editor/qscintilla/Qsci/qscistyledtext.h \
        ./editor/qscintilla/ListBoxQt.h \
        ./editor/qscintilla/SciClasses.h \
        ./editor/qscintilla/SciNamespace.h \
        ./editor/qscintilla/ScintillaQt.h \
        ./editor/include/ILexer.h \
        ./editor/include/Platform.h \
        ./editor/include/Sci_Position.h \
        ./editor/include/SciLexer.h \
        ./editor/include/Scintilla.h \
        ./editor/include/ScintillaWidget.h \
        ./editor/lexlib/Accessor.h \
        ./editor/lexlib/CharacterCategory.h \
        ./editor/lexlib/CharacterSet.h \
        ./editor/lexlib/LexAccessor.h \
        ./editor/lexlib/LexerBase.h \
        ./editor/lexlib/LexerModule.h \
        ./editor/lexlib/LexerNoExceptions.h \
        ./editor/lexlib/LexerSimple.h \
        ./editor/lexlib/OptionSet.h \
        ./editor/lexlib/PropSetSimple.h \
        ./editor/lexlib/StringCopy.h \
        ./editor/lexlib/StyleContext.h \
        ./editor/lexlib/SubStyles.h \
        ./editor/lexlib/WordList.h \
        ./editor/src/AutoComplete.h \
        ./editor/src/CallTip.h \
        ./editor/src/CaseConvert.h \
        ./editor/src/CaseFolder.h \
        ./editor/src/Catalogue.h \
        ./editor/src/CellBuffer.h \
        ./editor/src/CharClassify.h \
        ./editor/src/ContractionState.h \
        ./editor/src/Decoration.h \
        ./editor/src/Document.h \
        ./editor/src/EditModel.h \
        ./editor/src/Editor.h \
        ./editor/src/EditView.h \
        ./editor/src/ExternalLexer.h \
        ./editor/src/FontQuality.h \
        ./editor/src/Indicator.h \
        ./editor/src/KeyMap.h \
        ./editor/src/LineMarker.h \
        ./editor/src/MarginView.h \
        ./editor/src/Partitioning.h \
        ./editor/src/PerLine.h \
        ./editor/src/PositionCache.h \
        ./editor/src/RESearch.h \
        ./editor/src/RunStyles.h \
        ./editor/src/ScintillaBase.h \
        ./editor/src/Selection.h \
        ./editor/src/SplitVector.h \
        ./editor/src/Style.h \
        ./editor/src/UnicodeFromUTF8.h \
        ./editor/src/UniConversion.h \
        ./editor/src/ViewStyle.h \
        ./editor/src/XPM.h

SOURCES = \
        ./editor/qscintilla/qsciscintilla.cpp \
        ./editor/qscintilla/qsciscintillabase.cpp \
        ./editor/qscintilla/qsciabstractapis.cpp \
        ./editor/qscintilla/qsciapis.cpp \
        ./editor/qscintilla/qscicommand.cpp \
        ./editor/qscintilla/qscicommandset.cpp \
        ./editor/qscintilla/qscidocument.cpp \
        ./editor/qscintilla/qscilexer.cpp \
        ./editor/qscintilla/qscilexeravs.cpp \
        ./editor/qscintilla/qscilexerbash.cpp \
        ./editor/qscintilla/qscilexerbatch.cpp \
        ./editor/qscintilla/qscilexercmake.cpp \
        ./editor/qscintilla/qscilexercoffeescript.cpp \
        ./editor/qscintilla/qscilexercpp.cpp \
        ./editor/qscintilla/qscilexercsharp.cpp \
        ./editor/qscintilla/qscilexercss.cpp \
        ./editor/qscintilla/qscilexercustom.cpp \
        ./editor/qscintilla/qscilexerd.cpp \
        ./editor/qscintilla/qscilexerdiff.cpp \
        ./editor/qscintilla/qscilexerfortran.cpp \
        ./editor/qscintilla/qscilexerfortran77.cpp \
        ./editor/qscintilla/qscilexerhtml.cpp \
        ./editor/qscintilla/qscilexeridl.cpp \
        ./editor/qscintilla/qscilexerjava.cpp \
        ./editor/qscintilla/qscilexerjavascript.cpp \
        ./editor/qscintilla/qscilexerjson.cpp \
        ./editor/qscintilla/qscilexerlua.cpp \
        ./editor/qscintilla/qscilexermakefile.cpp \
        ./editor/qscintilla/qscilexermarkdown.cpp \
        ./editor/qscintilla/qscilexermatlab.cpp \
        ./editor/qscintilla/qscilexeroctave.cpp \
        ./editor/qscintilla/qscilexerpascal.cpp \
        ./editor/qscintilla/qscilexerperl.cpp \
        ./editor/qscintilla/qscilexerpostscript.cpp \
        ./editor/qscintilla/qscilexerpo.cpp \
        ./editor/qscintilla/qscilexerpov.cpp \
        ./editor/qscintilla/qscilexerproperties.cpp \
        ./editor/qscintilla/qscilexerpython.cpp \
        ./editor/qscintilla/qscilexerruby.cpp \
        ./editor/qscintilla/qscilexerspice.cpp \
        ./editor/qscintilla/qscilexersql.cpp \
        ./editor/qscintilla/qscilexertcl.cpp \
        ./editor/qscintilla/qscilexertex.cpp \
        ./editor/qscintilla/qscilexerverilog.cpp \
        ./editor/qscintilla/qscilexervhdl.cpp \
        ./editor/qscintilla/qscilexerxml.cpp \
        ./editor/qscintilla/qscilexeryaml.cpp \
        ./editor/qscintilla/qscimacro.cpp \
        ./editor/qscintilla/qsciprinter.cpp \
        ./editor/qscintilla/qscistyle.cpp \
        ./editor/qscintilla/qscistyledtext.cpp \
        ./editor/qscintilla/MacPasteboardMime.cpp \
        ./editor/qscintilla/InputMethod.cpp \
        ./editor/qscintilla/SciClasses.cpp \
        ./editor/qscintilla/ListBoxQt.cpp \
        ./editor/qscintilla/PlatQt.cpp \
        ./editor/qscintilla/ScintillaQt.cpp \
        ./editor/lexers/LexA68k.cpp \
        ./editor/lexers/LexAbaqus.cpp \
        ./editor/lexers/LexAda.cpp \
        ./editor/lexers/LexAPDL.cpp \
        ./editor/lexers/LexAsm.cpp \
        ./editor/lexers/LexAsn1.cpp \
        ./editor/lexers/LexASY.cpp \
        ./editor/lexers/LexAU3.cpp \
        ./editor/lexers/LexAVE.cpp \
        ./editor/lexers/LexAVS.cpp \
        ./editor/lexers/LexBaan.cpp \
        ./editor/lexers/LexBash.cpp \
        ./editor/lexers/LexBasic.cpp \
        ./editor/lexers/LexBatch.cpp \
        ./editor/lexers/LexBibTeX.cpp \
        ./editor/lexers/LexBullant.cpp \
        ./editor/lexers/LexCaml.cpp \
        ./editor/lexers/LexCLW.cpp \
        ./editor/lexers/LexCmake.cpp \
        ./editor/lexers/LexCOBOL.cpp \
        ./editor/lexers/LexCoffeeScript.cpp \
        ./editor/lexers/LexConf.cpp \
        ./editor/lexers/LexCPP.cpp \
        ./editor/lexers/LexCrontab.cpp \
        ./editor/lexers/LexCsound.cpp \
        ./editor/lexers/LexCSS.cpp \
        ./editor/lexers/LexD.cpp \
        ./editor/lexers/LexDiff.cpp \
        ./editor/lexers/LexDMAP.cpp \
        ./editor/lexers/LexDMIS.cpp \
        ./editor/lexers/LexECL.cpp \
        ./editor/lexers/LexEDIFACT.cpp \
        ./editor/lexers/LexEiffel.cpp \
        ./editor/lexers/LexErlang.cpp \
        ./editor/lexers/LexErrorList.cpp \
        ./editor/lexers/LexEScript.cpp \
        ./editor/lexers/LexFlagship.cpp \
        ./editor/lexers/LexForth.cpp \
        ./editor/lexers/LexFortran.cpp \
        ./editor/lexers/LexGAP.cpp \
        ./editor/lexers/LexGui4Cli.cpp \
        ./editor/lexers/LexHaskell.cpp \
        ./editor/lexers/LexHex.cpp \
        ./editor/lexers/LexHTML.cpp \
        ./editor/lexers/LexInno.cpp \
        ./editor/lexers/LexJSON.cpp \
        ./editor/lexers/LexKix.cpp \
        ./editor/lexers/LexKVIrc.cpp \
        ./editor/lexers/LexLaTeX.cpp \
        ./editor/lexers/LexLisp.cpp \
        ./editor/lexers/LexLout.cpp \
        ./editor/lexers/LexLua.cpp \
        ./editor/lexers/LexMagik.cpp \
        ./editor/lexers/LexMake.cpp \
        ./editor/lexers/LexMarkdown.cpp \
        ./editor/lexers/LexMatlab.cpp \
        ./editor/lexers/LexMetapost.cpp \
        ./editor/lexers/LexMMIXAL.cpp \
        ./editor/lexers/LexModula.cpp \
        ./editor/lexers/LexMPT.cpp \
        ./editor/lexers/LexMSSQL.cpp \
        ./editor/lexers/LexMySQL.cpp \
        ./editor/lexers/LexNimrod.cpp \
        ./editor/lexers/LexNsis.cpp \
        ./editor/lexers/LexNull.cpp \
        ./editor/lexers/LexOpal.cpp \
        ./editor/lexers/LexOScript.cpp \
        ./editor/lexers/LexPascal.cpp \
        ./editor/lexers/LexPB.cpp \
        ./editor/lexers/LexPerl.cpp \
        ./editor/lexers/LexPLM.cpp \
        ./editor/lexers/LexPO.cpp \
        ./editor/lexers/LexPOV.cpp \
        ./editor/lexers/LexPowerPro.cpp \
        ./editor/lexers/LexPowerShell.cpp \
        ./editor/lexers/LexProgress.cpp \
        ./editor/lexers/LexProps.cpp \
        ./editor/lexers/LexPS.cpp \
        ./editor/lexers/LexPython.cpp \
        ./editor/lexers/LexR.cpp \
        ./editor/lexers/LexRebol.cpp \
        ./editor/lexers/LexRegistry.cpp \
        ./editor/lexers/LexRuby.cpp \
        ./editor/lexers/LexRust.cpp \
        ./editor/lexers/LexScriptol.cpp \
        ./editor/lexers/LexSmalltalk.cpp \
        ./editor/lexers/LexSML.cpp \
        ./editor/lexers/LexSorcus.cpp \
        ./editor/lexers/LexSpecman.cpp \
        ./editor/lexers/LexSpice.cpp \
        ./editor/lexers/LexSQL.cpp \
        ./editor/lexers/LexSTTXT.cpp \
        ./editor/lexers/LexTACL.cpp \
        ./editor/lexers/LexTADS3.cpp \
        ./editor/lexers/LexTAL.cpp \
        ./editor/lexers/LexTCL.cpp \
        ./editor/lexers/LexTCMD.cpp \
        ./editor/lexers/LexTeX.cpp \
        ./editor/lexers/LexTxt2tags.cpp \
        ./editor/lexers/LexVB.cpp \
        ./editor/lexers/LexVerilog.cpp \
        ./editor/lexers/LexVHDL.cpp \
        ./editor/lexers/LexVisualProlog.cpp \
        ./editor/lexers/LexYAML.cpp \
        ./editor/lexlib/Accessor.cpp \
        ./editor/lexlib/CharacterCategory.cpp \
        ./editor/lexlib/CharacterSet.cpp \
        ./editor/lexlib/LexerBase.cpp \
        ./editor/lexlib/LexerModule.cpp \
        ./editor/lexlib/LexerNoExceptions.cpp \
        ./editor/lexlib/LexerSimple.cpp \
        ./editor/lexlib/PropSetSimple.cpp \
        ./editor/lexlib/StyleContext.cpp \
        ./editor/lexlib/WordList.cpp \
        ./editor/src/AutoComplete.cpp \
        ./editor/src/CallTip.cpp \
        ./editor/src/CaseConvert.cpp \
        ./editor/src/CaseFolder.cpp \
        ./editor/src/Catalogue.cpp \
        ./editor/src/CellBuffer.cpp \
        ./editor/src/CharClassify.cpp \
        ./editor/src/ContractionState.cpp \
        ./editor/src/Decoration.cpp \
        ./editor/src/Document.cpp \
        ./editor/src/EditModel.cpp \
        ./editor/src/Editor.cpp \
        ./editor/src/EditView.cpp \
        ./editor/src/ExternalLexer.cpp \
        ./editor/src/Indicator.cpp \
        ./editor/src/KeyMap.cpp \
        ./editor/src/LineMarker.cpp \
        ./editor/src/MarginView.cpp \
        ./editor/src/PerLine.cpp \
        ./editor/src/PositionCache.cpp \
        ./editor/src/RESearch.cpp \
        ./editor/src/RunStyles.cpp \
        ./editor/src/ScintillaBase.cpp \
        ./editor/src/Selection.cpp \
        ./editor/src/Style.cpp \
        ./editor/src/UniConversion.cpp \
        ./editor/src/ViewStyle.cpp \
        ./editor/src/XPM.cpp

TRANSLATIONS = \
        ./editor/qscintilla/qscintilla_cs.ts \
        ./editor/qscintilla/qscintilla_de.ts \
        ./editor/qscintilla/qscintilla_es.ts \
        ./editor/qscintilla/qscintilla_fr.ts \
        ./editor/qscintilla/qscintilla_pt_br.ts
